mutation AddAsset($asset: AssetInput) {
    addAsset(asset: $asset) {
        type
        value
    }
}

mutation UpdateAsset($asset: AssetUpdateInput) {
    updateAsset(asset: $asset) {
        type
        value
    }
}

mutation DeleteAsset($id: String!) {
    deleteAsset(id: $id)
}

mutation AddPriceRecord($assetId: String!, $price: Float!, $timestamp: String) {
    addPriceRecord(assetId: $assetId, price: $price, timestamp: $timestamp) {
        id
        assetId
        price
        timestamp
    }
}

mutation UpdatePriceRecord($id: Int!, $price: Float!, $timestamp: String!) {
    updatePriceRecord(id: $id, price: $price, timestamp: $timestamp) {
        id
        assetId
        price
        timestamp
    }
}

mutation DeletePriceRecord($id: Int!) {
    deletePriceRecord(id: $id)
}
